spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enabled_lazy_load_no_trans: true
  cache:
    cache-names: userCache
    caffeine:
      spec: expireAfterWrite=120s
server:
  port: 8080

userTask:
  openapi:
    dev-url: http://localhost:8080

logging:
  level:
    org:
    springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      hibernate: DEBUG
      jpa: DEBUG
      sql: DEBUG
      jwt: DEBUG
      userTask: DEBUG